enable "docker-compose only" mode & support prebuild scripts

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -59,6 +59,14 @@ __var_project_environment="$(to_upper "${PROJECT_NAME}")_ENVIRONMENT"
 PROJECT_ENVIRONMENT="${!__var_project_environment:-}"
 
 
+### Functions
+##############################################################################
+
+function is_docker_compose_only() {
+    grep "^\s*docker_compose_only: true\s*$" -q "${1}"
+}
+
+
 ### Coerce
 ##############################################################################
 
@@ -98,18 +106,63 @@ if [[ ${arg_s} = "${PROJECT_NAME}" ]]; then
 else 
   __stack="${arg_s}"
 fi
+__docker_compose_dir="${__dir}/${DIR_DEPLOYMENTS}/${arg_s}"
+__docker_compose_file="${__docker_compose_dir}/docker-compose.yml"
+__docker_compose_file_common="${__docker_compose_dir}/docker-compose.common.yml"
+__docker_compose_file_env="${__docker_compose_dir}/docker-compose.${PROJECT_ENVIRONMENT}.yml"
+if [[ ${arg_s} = "${PROJECT_NAME}" ]]; then
+  if [[ ! -s "${__docker_compose_file_common}" ]]; then
+    error "Docker compose file ${__docker_compose_file_common} is not found."
+    exit 1
+  elif [[ ! -s "${__docker_compose_file_env}" ]]; then
+    error "Docker compose file ${__docker_compose_file_env} is not found."
+    exit 1
+  fi
+fi
+__docker_compose_only="0"
+__docker_compose_args="--project-name ${__stack}"
+__docker_deploy_args=
+if [[ -s "${__docker_compose_file}" ]]; then
+  if is_docker_compose_only "${__docker_compose_file}"; then
+    __docker_compose_only="1"
+  fi
+  __docker_compose_args="${__docker_compose_args} --file ${__docker_compose_file}"
+  __docker_deploy_args="--compose-file ${__docker_compose_file}"
+elif [[ -s "${__docker_compose_file_common}" && -s "${__docker_compose_file_env}" ]]; then
+  if is_docker_compose_only "${__docker_compose_file_common}"; then
+    __docker_compose_only="1"
+  fi
+  __docker_compose_args="${__docker_compose_args} --file ${__docker_compose_file_common} --file ${__docker_compose_file_env}"
+  __docker_deploy_args="--compose-file ${__docker_compose_file_common} --compose-file ${__docker_compose_file_env}"
+else
+  error "Neither file \"docker-compose.yml\" nor files \"docker-compose.common.yml\" and" \
+        "\"docker-compose.${PROJECT_ENVIRONMENT}.yml\" have been found in ${__docker_compose_dir}."
+fi
 
 if [[ ${arg_p:?} = "1" ]]; then
   
-  exec_with_debug docker stack ps "${__stack}"
+  if [[ "${__docker_compose_only}" = "1" ]]; then
+    exec_with_debug docker-compose "${__docker_compose_args}" ps
+  else
+    exec_with_debug docker stack ps "${__stack}"
+  fi
   
-elif [[ ${arg_s:?} = "1" ]]; then
+elif [[ ${arg_l:?} = "1" ]]; then
   
-  exec_with_debug docker stack services "${__stack}"
+  if [[ "${__docker_compose_only}" = "1" ]]; then
+    exec_with_debug docker-compose "${__docker_compose_args}" ps
+  else
+    exec_with_debug docker stack services "${__stack}"
+  fi
 
 elif [[ ${arg_r:?} = "1" ]]; then
   
-  exec_with_debug docker stack rm "${__stack}"  
+  if [[ "${__docker_compose_only}" = "1" ]]; then
+    exec_with_debug docker-compose "${__docker_compose_args}" stop
+    exec_with_debug docker-compose "${__docker_compose_args}" rm --force
+  else
+    exec_with_debug docker stack rm "${__stack}"  
+  fi
   
 else
   
@@ -117,33 +170,12 @@ else
     info "Ensure all the images are built."
     "${__dir}"/build -a
   fi
-  
-  info "Deploy stack ${__stack} into swarm."
-  __docker_compose_dir="${__dir}/${DIR_DEPLOYMENTS}/${arg_s}"
-  __docker_compose_file="${__docker_compose_dir}/docker-compose.yml"
-  __docker_compose_file_common="${__docker_compose_dir}/docker-compose.common.yml"
-  __docker_compose_file_env="${__docker_compose_dir}/docker-compose.${PROJECT_ENVIRONMENT}.yml"
-  if [[ ${arg_s} = "${PROJECT_NAME}" ]]; then
-    if [[ ! -s "${__docker_compose_file_common}" ]]; then
-      error "Docker compose file ${__docker_compose_file_common} is not found."
-      exit 1
-    elif [[ ! -s "${__docker_compose_file_env}" ]]; then
-      error "Docker compose file ${__docker_compose_file_env} is not found."
-      exit 1
-    fi
-  fi
-  if [[ -s "${__docker_compose_file}" ]]; then
-    exec_with_debug docker stack deploy \
-      --compose-file "${__docker_compose_file}" \
-      "${__stack}"
-  elif [[ -s "${__docker_compose_file_common}" && -s "${__docker_compose_file_env}" ]]; then
-    exec_with_debug docker stack deploy \
-      --compose-file "${__docker_compose_file_common}" \
-      --compose-file "${__docker_compose_file_env}" \
-      "${__stack}"
+  if [[ "${__docker_compose_only}" = "1" ]]; then
+    info "Stack ${__stack} is for docker-compose only. Deploy with \"docker-compose up\"."
+    exec_with_debug docker-compose "${__docker_compose_args}" up --detach
   else
-    error "Neither file \"docker-compose.yml\" nor files \"docker-compose.common.yml\" and" \
-          "\"docker-compose.${PROJECT_ENVIRONMENT}.yml\" have been found in ${__docker_compose_dir}."
+    info "Deploy stack ${__stack} into swarm."
+    exec_with_debug docker stack deploy "${__docker_deploy_args}" "${__stack}"  
   fi
   
 fi
